### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by ChristofLuytenGFI** [microsoftgraph/nodejs-sentiment-bot-sample#1]
When you try "npm start", there is an error when TypeScript is not installed. Maybe you should mention that or add it to the dependencies.

**Comment by jbeltranluna** [comment]
I also get a POST Socket hang up for every message I send in the Bot Emulator and cannot test the example

**Comment by jamescro** [comment]
Thanks for catching this. I've added TypScript to the prerequisites section.
