### ISSUE TITLE
Socket Hang Up

### ISSUE THREAD

**Issue by jbeltranluna** [microsoftgraph/nodejs-sentiment-bot-sample#2]
I always get a POST Socket hang up message for every message I send in the Bot Emulator and cannot test the example

**Comment by jamescro** [comment]
I can reproduce that error when I use the non-SSL URL: http://localhost:3980/api/messages
Can you verify that the web application is running and accessible at https://localhost:3980/api/messages?

**Comment by jasonjoh** [comment]
Closing this as we are archiving this repository and no longer maintaining it.
